[package]
name = "smoke"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
itertools = "0.10.3"
palette = "0.6.0"
plotters = "^0.3.1"
rand = "0.6.0"
