name: "2022 tests"
on:
  pull_request:
  push:
    paths:
      - 2022/**
      - .github/workflows/2022.yml
jobs:
  zig-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2022
    steps:
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.10.0
    - run: zig build test
